#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_tracy = env_modules.Clone()
tracy_dir = "./tracy/public/"


if "tracy_enable" in env and (env["tracy_enable"] == "yes" or env["tracy_enable"] == "true"):
    
    tracy_src = [
        "TracyClient.cpp",
    ]

    print("-------------TRACY_ENABLE--------------")
    env_tracy.Append(CPPDEFINES=["TRACY_ENABLE"])
    env_modules.Append(CPPDEFINES=["TRACY_ENABLE"])
    env.Append(CPPDEFINES=["TRACY_ENABLE"])

    env_tracy.add_source_files(env.modules_sources, tracy_dir+"TracyClient.cpp")
    #env_tracy.add_source_files(env.modules_sources, "*.cpp")
    
if "tracy_on_demand" in env and env["tracy_on_demand"]:

    tracy_src = [
        "TracyClient.cpp",
    ]

    env_tracy.Append(CPPDEFINES=["TRACY_ON_DEMAND"])
    env_modules.Append(CPPDEFINES=["TRACY_ON_DEMAND"])
    env.Append(CPPDEFINES=["TRACY_ON_DEMAND"])

env_tracy.add_source_files(env.modules_sources, "*.cpp")



